### ISSUE TITLE
Unable to tell difference between 2 namespaces that are the same but different assembly

### ISSUE THREAD

**Issue by danwalmsley** [OmniGUI/OmniXAML#109]
OmniXaml was unable to resolve the second of these 2 namespaces when used together.
xmlns:Controls="clr-namespace:AvalonStudio.Controls;assembly=AvalonStudio"  
xmlns:cont="clr-namespace:AvalonStudio.Controls;assembly=AvalonStudio.Extensibility"

omnixaml seems to do lookup in the first one.

**Comment by SuperJMN** [comment]
Could you post a simple example? Thank you!
