### ISSUE TITLE
How can I load, find and replace specific values from a WPF XAML file?

### ISSUE THREAD

**Issue by Emasoft** [OmniGUI/OmniXAML#115]
This is a cool library, but there is no much documentation.

I need to load, find and replace specific values from a WPF XAML file. I'm working on a porting of a UI project and I need to apply a transformation to all coordinates/measures/font sizes/etc. in a bunch of XAML files.

How can I do that using OmniXAML? I need to use OmniXAML in a simple command line executable, so I'm not interested in visualization. I'm working on a Mac OS X, with Xamarin Studio.

Thanks!

**Comment by SuperJMN** [comment]
Hi! Thanks for your interest. Can you give me some example? By the way, you could take a look to the SampleModel project to see how to load some XAML. And... yes, there is not documentation right now :(
