### ISSUE TITLE
Supporting immutable types

### ISSUE THREAD

**Issue by grokys** [OmniGUI/OmniXAML#75]
Currently if a type has no default constructor, it is not usable from XAML.

(Ok, there's the [x:Arguments](http://stackoverflow.com/questions/1083159/calling-a-parametrized-constructor-from-xaml) directive, but it's ugly as hell and not even supported anywhere)

Immutable types are becoming more and more common, there should be a better way to handle them. For example in Perspex, our `SolidColorBrush` is immutable and so it's not creatable from XAML!

I propose a simple way to handle immutable types:
- If trying to create a class with no default constructor, get the available constructors
- Try to match each property defined in XAML to a constructor argument, by name
- Try to convert each property to the argument type
- If we have a constructor we can call, call it!
- Try to assign remaining properties in the usual way.

For example:

```
<SolidColorBrush Color="Red"/>
```

Would call the:

```
SolidColorBrush(Color red)
```

Constructor.

**Comment by SuperJMN** [comment]
That should work for object, but what about collections?

**Comment by jogibear9988** [comment]
if you have more matching constructors, wich one should be usef?

**Comment by SuperJMN** [comment]
@jogibear9988 My approach is that you can control that. A default pick strategy will come as default.

**Comment by SuperJMN** [comment]
Hi people! I'm about to implement this, BUT:

I have reached a major roadblock: collections. How are we supposed to create an immutable collection in XAML? The parsing relies on collections that are already instantiated and use the Add method to add items as they come (there is no lookahead in this phase).

Do you have any idea?

**Comment by SuperJMN** [comment]
I'm making big progress with this!

**Comment by SuperJMN** [comment]
OmniXAML v2 will be able to instantiate immutables. Stay tuned.
